### ISSUE TITLE
TraCI Client Access 

### ISSUE THREAD

**Issue by sangitatukai** [guibaraujo/ndn4ivc#16]
Is it possible to access the traCI client of a node from any other class except tms-consumer.cc and tmc-provider.cc ? 

I want to know the present RoadID and Route of vehicle from the ndn-cxx.nfd.Forwarder:onIncomingData() ?
Is there any other way to get this except using traCI client ?

Any help will be appreciated.

**Comment by sangitatukai** [comment]
Hi @guibaraujo  any insight on this ? 
It will be helpful.

**Comment by guibaraujo** [comment]
It's possible. You can check out the new its-* scenario to understand how to adapt to your scenario.
